DROP TABLE IF EXISTS notas;
CREATE TABLE notas (_id INTEGER PRIMARY KEY AUTOINCREMENT, categoria TEXT NOT NULL, titulo TEXT NOT NULL, descripcion TEXT NOT NULL, icono INTEGER NOT NULL);
INSERT INTO notas VALUES (01, 'REUNION', 'CUMPLEAÑOS DE MARIA, 5PM', 'CALLE TIARA Nº 13, BAR LOS CHOPOS', 2131230842);
INSERT INTO notas VALUES (02, 'AVISO', 'HACER LA CAMA', 'ANTES DE QUE SE ENTERE TU MADRE', 2131230813);
INSERT INTO notas VALUES (03, 'VARIOS', 'LISTA DE LA COMPRA', 'TOMATES, BERENJENAS, POLLO, ARROZ, LENTEJAS', 2131230845);